services:
  - type: web
    name: ai-image-generator-fullstack
    env: node
    region: oregon
    plan: free
    buildCommand: npm install && npm run build && cd server && npm install --production
    startCommand: cd server && node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: HUGGING_FACE_TOKEN
        sync: false 